export enum RequestState {
    SEARCH_IN_PROGRESS = 'SEARCH_IN_PROGRESS',
    SEARCH_RESULT_EMPTY = 'SEARCH_RESULT_EMPTY',
    SEARCH_RESULT_FOUND = 'SEARCH_RESULT_FOUND',
    SEARCH_REQUEST_EMPTY = 'SEARCH_REQUEST_EMPTY',
    SEARCH_ERROR = 'SEARCH_ERROR',
}
